---
- hosts: "localhost"
  vars_files:
  - vars_ohio.yml

  tasks:
  - name: "login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"
        password: "{{mgmt_password}}"
        management: "{{mgmt_server}}"
      fingerprint: "{{mgmt_fingerprint}}"
    register: login_response

  - name: "Add CheckMatesDemo group"
    check_point_mgmt:
      command: add-group
      parameters:
        name: "CheckMatesDemo"
      session-data: "{{login_response}}"

  - name: "Add RyanHost1 Host"
    check_point_mgmt:
      command: add-host
      parameters:
        name: "RyanHost1"
        ip-address: "123.123.123.123"
        color: "red"
      session-data: "{{login_response}}"

  - name: "Add RyanHost2 Host"
    check_point_mgmt:
      command: add-host
      parameters:
        name: "RyanHost2"
        ip-address: "124.124.124.124"
        color: "red"
      session-data: "{{login_response}}"

  - name: "publish"
    check_point_mgmt:
      command: publish
      session-data: "{{login_response}}"

  - name: "logout"
    check_point_mgmt:
      command: logout
      session-data: "{{login_response}}"

