---
- hosts: "localhost"
  vars_files:
  - vars.yml

  tasks:

  - name: Wait up to 300 seconds for SIC port 18211 to Open
    wait_for:
      port: 18211
      host: "{{ target }}"
      delay: 10
    connection: local

  - name: "login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"
        password: "{{mgmt_password}}"
        management: "{{mgmt_server}}"
      fingerprint: "{{mgmt_fingerprint}}"
    register: login_response



  - name: "Create SimpleGateway {{hostname}} at {{eth0_ipv4}}"
    check_point_mgmt:
      command: add-simple-gateway 
      parameters:
        name: "{{hostname}}"
        ipv4-address: "{{eth0_ipv4}}" 
        color: blue
        firewall: "true"
        version: "R80.10"
        ips: "true"
        one-time-password: "{{sickey}}"
        interfaces:
        -  name: eth0
           ipv4-address: "{{eth0_ipv4}}" 
           ipv4-network-mask: 255.255.255.0
           topology: External
           anti-spoofing: "true"
        -  name: eth1
           ipv4-address: "{{eth1_ipv4}}" 
           ipv4-network-mask: 255.255.255.0
           topology: Internal
           anti-spoofing: "true"
           topology-settings:
             ip-address-behind-this-interface: "network defined by the interface ip and net mask"
      session-data: "{{login_response}}"        

  - name: "publish"
    check_point_mgmt:
      command: publish
      session-data: "{{login_response}}"

  - name: "Push Access Policy"
    check_point_mgmt:
      command: install-policy
      parameters:
        policy-package: "CheckMates_Demo_Policy"
        access: "true"
        threat-prevention: "false"
        targets:
          -  "{{hostname}}"
      session-data: "{{login_response}}"

  - name: "Push Threat Policy"
    check_point_mgmt:
      command: install-policy
      parameters:
        policy-package: "CheckMates_Demo_Policy"
        access: "false"
        threat-prevention: "true"
        targets:
          -  "{{hostname}}"
      session-data: "{{login_response}}"
  
  - name: "logout"
    check_point_mgmt:
      command: logout
      session-data: "{{login_response}}"
